apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: delete-app
  namespace: fybrik-notebook-sample
spec:
  selector:
   workloadSelector:
     matchLabels: {}
  appInfo:
    intent: Fraud Detection
    role: Security
  data:
    - dataSetID: 'fybrik-notebook-sample/paysim-csv'
      flow: delete
      requirements: {}
